L = {} -- Polish Content Strings by meerfi

///////////////////// -- [[ Scavenger's Spoils ]] --
-- Weapons
ws = "tacrp_pa_"
w = ws .. "auto5"
-- L["wep." .. w .. ".name.full"] = "Browning Auto 5"
-- L["wep." .. w .. ".name"] = "Auto 5"
-- L["wep." .. w .. ".desc"] = "Old school automatic shotgun. Small caliber shells have good range and firerate, but poor stopping power."
-- L["wep." .. w .. ".desc.quote"] = "\"Line 'em up and knock 'em down.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Browning Arms"
-- L["wep." .. w .. ".credits"] = "Model: RedRogueXIII, An Aggressive Napkin \nTextures: Futon \nSounds: Futon \nAnimations: Tactical Intervention"

w = ws .. "automag3"
-- L["wep." .. w .. ".name.full"] = "AMT AutoMag III"
-- L["wep." .. w .. ".name"] = "AutoMag III"
-- L["wep." .. w .. ".desc"] = "Stainless steel pistol chambered in an obscure cartridge. Not very powerful for a magnum pistol, but has good capacity."
-- L["wep." .. w .. ".desc.quote"] = "\"You were always the best. Nobody ever came close.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Arcadia Machine & Tool"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Degenerate Dak \nSounds: Navaro \nAnimations: Tactical Intervention"

w = ws .. "awp"
-- L["wep." .. w .. ".name.full"] = "AI AWM-F"
-- L["wep." .. w .. ".name"] = "AWM"
-- L["wep." .. w .. ".desc"] = "Robust magnum sniper with unmatched power and accuracy. A counter-terrorist favourite.\nEquipped with a 12x scope by default."
-- L["wep." .. w .. ".desc.quote"] = "\"He's a madman, a scientist, and a sharpshooter.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Accuracy International"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c \nTextures: Bullethead & Kimono \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "coachgun"
-- L["wep." .. w .. ".name.full"] = "Stoeger Coachgun"
-- L["wep." .. w .. ".name"] = "Coachgun"
-- L["wep." .. w .. ".desc"] = "Double barrel shotgun from the Old West.\nCumbersome and inaccurate, but still packs a punch."
-- L["wep." .. w .. ".desc.quote"] = "Lock, stock, and two smoking barrels."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Stoeger"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Fistful of Frags (Macaroane, Paul68Rageous, Tigg) \nSounds: Fistful of Frags, rzen1th \nAnimations: 8Z"

w = ws .. "cz75"
-- L["wep." .. w .. ".name.full"] = "CZ-75 Automatic"
-- L["wep." .. w .. ".name"] = "CZ-75"
-- L["wep." .. w .. ".desc"] = "Automatic variant of the quintessential \"Wonder Nine\".\nFast firing and controllable, but capacity is low."
-- L["wep." .. w .. ".desc.quote"] = "The pinnacle of semi-automatic handgun evolution."
-- L["wep." .. w .. ".trivia.manufacturer"] = "CZ Uherský Brod"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Arby \nSounds: Hk, Vunsunta, xLongWayHome, Strelok, Cas, IceFluxx \nAnimations: Tactical Intervention"

w = ws .. "dual_makarov"

-- L["wep." .. w .. ".name"] = "Dual Makarovs"
-- L["wep." .. w .. ".desc"] = "A pair of Soviet pistols to compensate for the lack of firepower with just one. Minimal recoil, but lethality remains poor past point blank."
-- L["wep." .. w .. ".desc.quote"] = "\"Finish the job, James! Blow them all to hell!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Izhevsk Mechanical Plant"
-- L["wep." .. w .. ".credits"] = "Assets: TehSnake \nSounds: Hk, Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "fnmag"
-- L["wep." .. w .. ".name"] = "FN MAG"
L["wep." .. w .. ".desc"] = "Niezwykle ciężki \"lekki\" karabin maszynowy, który łączy cechy LMG i broni stacjonarnej. Posiada niemal niekończący się magazynek."
L["wep." .. w .. ".desc.quote"] = "\"Nie możesz mnie tu zostawić z tymi... zwierzętami.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Fabrique National"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Call to Arms \nAnimations: Tactical Intervention \nPorted by: Arctic"

w = ws .. "fort12"
-- L["wep." .. w .. ".name"] = "Fort-12"
L["wep." .. w .. ".desc"] = "Ekonomiczny ukraiński pistolet rzadko spotykany poza Europą Wschodnią. Niska moc obalająca, ale poręczny i prawdopodobnie przetrwa kilka nadprzyrodzonych katastrof."
L["wep." .. w .. ".desc.quote"] = "Znajdź Streloka. Zabić Streloka?"
-- L["wep." .. w .. ".trivia.manufacturer"] = "RPC Fort"
-- L["wep." .. w .. ".credits"] = "Assets: S.T.A.L.K.E.R. (ported by modderfreak) \nAnimations: Tactical Intervention"

w = ws .. "hipoint"
-- L["wep." .. w .. ".name.full"] = "Hi-Point 995"
-- L["wep." .. w .. ".name"] = "Hi-Point"
-- L["wep." .. w .. ".desc"] = "Infamous semi-automatic pistol-caliber carbine.\nReasonably powerful... when it works, which is never."
-- L["wep." .. w .. ".desc.quote"] = "\"That chandelier was expensive, asshole!!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Hi-Point Firearms"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Yumyumshisha \nSounds: Obsidian \nAnimations: Tactical Intervention"

w = ws .. "ithaca"
-- L["wep." .. w .. ".name"] = "Ithaca 37"
L["wep." .. w .. ".desc"] = "Strzelba z czasów II wojny światowej, używana przez policję i wojsko. Zdolna do szybkiego ognia, ale ma słabe rozproszenie i niską pojemność amunicji."
-- L["wep." .. w .. ".desc.quote"] = "\"What? It was obvious! He's the RED Spy!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Ithaca Gun Company"
-- L["wep." .. w .. ".credits"] = "Model: Millenia \nTextures: Poux \nSounds: Strelok \nAnimations: Tactical Intervention"

w = ws .. "klin"
-- L["wep." .. w .. ".name.full"] = "PP-9 Klin"
-- L["wep." .. w .. ".name"] = "Klin"
-- L["wep." .. w .. ".desc"] = "Simple, lightweight, cheap machine pistol.\nHas a high fire rate but is prone to jamming."
-- L["wep." .. w .. ".desc.quote"] = "\"Eyy, importnyy? FUCK OFF. Ponyl?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Izhmash"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Teh Snake \nAnimations: Tactical Intervention"

w = ws .. "ksg12"
-- L["wep." .. w .. ".name.full"] = "KelTec KSG"
-- L["wep." .. w .. ".name"] = "KSG"
-- L["wep." .. w .. ".desc"] = "A bizarre bullpup, twin-tubed, pump-action shotgun. Super high capacity offset by extreme heft."
-- L["wep." .. w .. ".desc.quote"] = "\"Hey! Quit eyeballing the chicks.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kel-Tec CNC Industries"
-- L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nSounds: Infinity Ward & Navarro \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "lapd"
-- L["wep." .. w .. ".name.full"] = "LAPD 2019 Blaster"
-- L["wep." .. w .. ".name"] = "LAPD 2019"
-- L["wep." .. w .. ".desc"] = "Gunsmith-custom based on an iconic film weapon, featuring excellent handling and an integrated laser sight."
-- L["wep." .. w .. ".desc.quote"] = "\"Quite an experience to live in fear, isn't it? That's what it is to be a slave.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Steyr, Charter Arms"
-- L["wep." .. w .. ".credits"] = "Assets: Fallout: New Vegas \nAnimations: Tactical Intervention, Fesiug, 8Z"

w = ws .. "lewis"
L["wep." .. w .. ".name"] = "Karabin Lewis"
L["wep." .. w .. ".desc"] = "Karabin maszynowy zasilany z tacy, chłodzony wodą, z dość małym magazynkiem."
L["wep." .. w .. ".desc.quote"] = "\"Wszyscy z drogi!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Lewis Automatic Machine Gun Company"
-- L["wep." .. w .. ".credits"] = "Assets: Verdun \nAnimations: Tactical Intervention"

w = ws .. "luty"
-- L["wep." .. w .. ".name"] = "Luty SMG"
-- L["wep." .. w .. ".desc"] = "Homemade SMG made as protest against UK firearm regulations. The first few shots in a burst have increased firerate, compensating for the weapon's terrible accuracy."
-- L["wep." .. w .. ".desc.quote"] = "\"Let us never succumb to the evil doctrine of the antigun movement.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "P.A. Luty"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Vasily \nSounds: New World Interactive, Firearms: Source \nAnimations: Tactical Intervention"

w = ws .. "m79"
-- L["wep." .. w .. ".name"] = "M79"
L["wep." .. w .. ".desc"] = "Granatnik z długą lufą i kolbą z drewna z dżungli. Precyzyjny i ma szybką prędkość początkową, ale jest dość ciężki."
L["wep." .. w .. ".desc.quote"] = "\"Goooooooooooooood morning, Wietnam!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Springfield Armory"
-- L["wep." .. w .. ".credits"] = "Model: EdisLeado \nTextures: Millenia \nSounds: Firearms: Source \nAnimations: speedonerd & 8Z"

w = ws .. "m202"
-- L["wep." .. w .. ".name.full"] = "M202 FLASH"
-- L["wep." .. w .. ".name"] = "M202"
-- L["wep." .. w .. ".desc"] = "Incendiary rocket launcher with four shots. Rockets ignite targets but have low damage and splash radius
-- L["wep." .. w .. ".desc.quote"] = "\"Fire and forget!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Northrop Electro-Mechanical Division"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "madsen"
-- L["wep." .. w .. ".name"] = "Madsen M-50"
L["wep." .. w .. ".desc"] = "Opłacalny duński SMG, który jest łatwy w użyciu, ale ma nieimponującą siłę ognia. Celownik nie może być montowany z powodu górnego uchwytu do ładowania."
L["wep." .. w .. ".desc.quote"] = "\"Czy wyrzekasz się Szatana... I wszystkich jego dzieł?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Dansk Industri Syndikat"
-- L["wep." .. w .. ".credits"] = "Model & Textures: jesamabin \nSounds: xLongWayHome \nAnimations: Tactical Intervention, 8Z"

w = ws .. "makarov"
-- L["wep." .. w .. ".name.full"] = "Makarov PM"
-- L["wep." .. w .. ".name"] = "PM"
L["wep." .. w .. ".desc"] = "Masowo produkowany radziecki pistolet boczny zaprojektowany do częstego noszenia i rzadkiego strzelania. Skuteczność jest słaba poza zasięgiem punktowym."
-- L["wep." .. w .. ".desc.quote"] = "\"You're listening to Apocalypse Radio. The only surviving radio station for miles.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Izhevsk Mechanical Plant"
-- L["wep." .. w .. ".credits"] = "Assets: TehSnake \nSounds: Hk, Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "mosin"
-- L["wep." .. w .. ".name.full"] = "Mosin-Nagant 91/30"
-- L["wep." .. w .. ".name"] = "M91/30"
-- L["wep." .. w .. ".desc"] = "Mass production Soviet bolt-action rifle. Infantry model cycles faster but is inaccurate; equip a scope for increased accuracy at cost of firerate."
-- L["wep." .. w .. ".desc.quote"] = "\"One out of two gets a rifle, one without follows him!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Red Orchestra 2 \nSounds: Red Orchestra 2, rzen1th \nAnimations: Cry of Fear, Lazarus, 8Z"

w = ws .. "oa93"
-- L["wep." .. w .. ".name.full"] = "Olympic Arms OA-93"
-- L["wep." .. w .. ".name"] = "OA-93"
-- L["wep." .. w .. ".desc"] = "AR-15 derived pistol with a top charging handle and no buffer tube. Designed to circumvent legal restrictions, but this one is ironically modified to fire in full auto."
-- L["wep." .. w .. ".desc.quote"] = "\"The most absurdly engineered way to say 'fuck you!' I've ever come across.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Olympic Arms"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Tuuttipingu, edited by 8Z \nSounds: NightmareMutant, Teh Strelok \nAnimations: Tactical Intervention"

w = ws .. "obrez"
-- L["wep." .. w .. ".name.full"] = "Remington 700 \"Obrez\""
-- L["wep." .. w .. ".name"] = "Obrez"
L["wep." .. w .. ".desc"] = "Skrócony karabin myśliwski zbudowany przez osoby pozbawione broni bocznej, aby był zastępnikiem ukrytego pistoletu. Modyfikacja poważnie szkodzi dokładności i wydajności na dystansie."
L["wep." .. w .. ".desc.quote"] = "\"Yippee-yay, nie będzie dzwonków ślubnych na dziś...\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Remington Arms, Bubba"
-- L["wep." .. w .. ".credits"] = "Assets: Bethesda Game Studios \nAnimations: Tactical Intervention \nPorted by: Arctic"

w = ws .. "ots33"
-- L["wep." .. w .. ".name.full"] = "OTs-33 Pernach"
-- L["wep." .. w .. ".name"] = "OTs-33"
L["wep." .. w .. ".desc"] = "Rosyjski pistolet maszynowy o niskim odrzucie, zaprojektowany dla sił paramilitarnych."
-- L["wep." .. w .. ".desc.quote"] = "\"I hope this hurts.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "KBP Instrument Design Bureau"
-- L["wep." .. w .. ".credits"] = "Model: Kimono \nTextures: Kimono, Millenia \nSounds: iFlip, Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "p2a1"
-- L["wep." .. w .. ".name.full"] = "HK P2A1"
-- L["wep." .. w .. ".name"] = "P2A1"
-- L["wep." .. w .. ".desc"] = "Single-shot flare pistol for signaling and illumination use.\nStandard round has a weak incendiary explosion. Can load a variety of payloads, including some shotshell types."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model & Textures: New World Interactive \nSounds: Raising The Bar: Redux, speedonerd \nAnimations: 8Z"

w = ws .. "ppsh"
-- L["wep." .. w .. ".name"] = "PPSh-41"
-- L["wep." .. w .. ".desc"] = "Soviet SMG with a high fire rate and suitably massive but unreliable drum magazine. Accuracy is non-existent and very much optional."
-- L["wep." .. w .. ".desc.quote"] = "Ура!"
-- L["wep." .. w .. ".trivia.manufacturer"] = "Various"
-- L["wep." .. w .. ".credits"] = "Model: Tripwire Interactive \nTextures: Rus_Ivan \nAnimations: Tactical Intervention, edited by speedonerd \nSounds: Rus_Ivan"

w = ws .. "python"
-- L["wep." .. w .. ".name.full"] = "Colt Python"
-- L["wep." .. w .. ".name"] = "Python"
L["wep." .. w .. ".desc"] = "Rzadki rewolwer o reputacji precyzyjnej i mocnej broni. Do strzelania jedną ręką; styl kowbojski."
L["wep." .. w .. ".desc.quote"] = "\"Kiedy musisz strzelać, strzelaj. Nie mów.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Model: Aggressive Napkin \nTextures: Teh Snake \nSounds: Vunsunta, XLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "rhino60ds"
-- L["wep." .. w .. ".name.full"] = "Chiappa Rhino 60DS"
-- L["wep." .. w .. ".name"] = "Rhino 60DS"
-- L["wep." .. w .. ".desc"] = "Modern long barrel revolver with hexagonal cylinder.\nBulky and has a heavy trigger, but recoil control is excellent."
-- L["wep." .. w .. ".desc.quote"] = "\"It's simple: overspecialize, and you breed in weakness. It's a slow death.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Chiappa Firearms"
-- L["wep." .. w .. ".credits"] = "Assets: Warface, ported by Dorian15 \nAnimations: Tactical Intervention"

w = ws .. "sako85"
-- L["wep." .. w .. ".name"] = "Sako 85"
L["wep." .. w .. ".desc"] = "Prosty, wytrzymały karabin myśliwski bez miejsca na taktyczne bzdury. Wyposażony w regulowany celownik 6x."
-- L["wep." .. w .. ".desc.quote"] = "Get a girl who loves you for your braaaains."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SAKO"
-- L["wep." .. w .. ".credits"] = "Assets: No More Room In Hell \nAnimations: Tactical Intervention"

w = ws .. "scorpionevo"
-- L["wep." .. w .. ".name.full"] = "CZ Scorpion EVO 3"
-- L["wep." .. w .. ".name"] = "Scorpion EVO"
-- L["wep." .. w .. ".desc"] = "Modern SMG with a extremely high rate of fire and intense recoil."
-- L["wep." .. w .. ".desc.quote"] = "Not to be confused with the vz. 61."
-- L["wep." .. w .. ".trivia.manufacturer"] = "CZ Uherský Brod"
-- L["wep." .. w .. ".credits"] = "Assets: Warface, Ghost1592365 \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "shorty"
-- L["wep." .. w .. ".name.full"] = "Serbu Super Shorty"
-- L["wep." .. w .. ".name"] = "Shorty"
L["wep." .. w .. ".desc"] = "Niestandardowa modyfikacja odbiornika Mossberg 88, przeznaczona do ekstremalnego ukrywania. Jednak poświęca precyzję i pojemność. Pasuje do kabur bocznych."
L["wep." .. w .. ".desc.quote"] = "\"Shawty poszła nisko, nisko, nisko, nisko...\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Serbu Firearms"
-- L["wep." .. w .. ".credits"] = "Assets: Millennia \nAnimations: Tactical Intervention \nPorted by: Arctic"

w = ws .. "sks"
-- L["wep." .. w .. ".name"] = "SKS"
-- L["wep." .. w .. ".desc"] = "Soviet semi-automatic rifle intended to complement the AK. A well-rounded medium range firearm."
-- L["wep." .. w .. ".desc.quote"] = "\"Don't breathe.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arsenal"
-- L["wep." .. w .. ".credits"] = "Assets: Firearms: Source \nAnimations: Tactical Intervention"

w = ws .. "smle"
-- L["wep." .. w .. ".name.full"] = "Lee-Enfield Mk III*"
-- L["wep." .. w .. ".name"] = "Lee-Enfield"
-- L["wep." .. w .. ".desc"] = "Mass production British bolt-action rifle with high capacity."
-- L["wep." .. w .. ".desc.quote"] = "\"It was all so easy.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Royal Small Arms Factory"
-- L["wep." .. w .. ".credits"] = "Assets: Cry of Fear \nAnimations: Cry of Fear, Lazarus"

w = ws .. "stg44"
-- L["wep." .. w .. ".name.full"] = "Sturmgewehr 44"
-- L["wep." .. w .. ".name"] = "StG 44"
-- L["wep." .. w .. ".desc"] = "Vintage assault rifle, considered by many to be the first of its kind. Somewhat powerful but prone to malfunctions."
-- L["wep." .. w .. ".desc.quote"] = "\"Mein carbine did not kill you? I will use gas! More gas!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "C.G. Haenel"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Tuuttipingu \nSounds: Navaro, Project Reality"

w = ws .. "svt40"
-- L["wep." .. w .. ".name"] = "SVT-40"
L["wep." .. w .. ".desc"] = "Karabin samopowtarzalny z okresu II wojny światowej zaprojektowany do ekstremalnej produkcji masowej. Potężny, ale nieprecyzyjny i niewiarygodny. Ograniczone wybory optyki."
-- L["wep." .. w .. ".desc.quote"] = "\"It's a sign that the Germans are starting to shit their pants!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arsenal"
-- L["wep." .. w .. ".credits"] = "Model: MrRifleman \nTextures: BuLL5H1T"

w = ws .. "svu"
-- L["wep." .. w .. ".name.full"] = "Dragunov SVU"
-- L["wep." .. w .. ".name"] = "SVU"
-- L["wep." .. w .. ".desc"] = "Bullpup modernized model of the SVD. Has good handling but average effective range.\nEquipped with a 6x scope by default."
-- L["wep." .. w .. ".desc.quote"] = "\"It's all just about perpective.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "KBP Instrument Design Bureau"
-- L["wep." .. w .. ".credits"] = "Assets: B0T \nSounds: NightmareMutant, sHiBaN, xLongWayHome \nAnimations: speedonerd"

w = ws .. "sw10"
-- L["wep." .. w .. ".name.full"] = "SW Model 10"
-- L["wep." .. w .. ".name"] = "SW M10"
-- L["wep." .. w .. ".desc"] = "An iconic revolver favored by cops and criminals alike.\nChambered in a non-magnum cartridge, so it's easy to handle but not that powerful."
-- L["wep." .. w .. ".desc.quote"] = "\"Who's 'we', sucka?\" \"Smith and Wesson, and me.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
-- L["wep." .. w .. ".credits"] = "Model: Harry Ridgeway, MediocrityGoggles \nTextures: Millenia \nSounds: Bethesda, Obsidian \nAnimations: Tactical Intervention"

w = ws .. "sw686"
-- L["wep." .. w .. ".name.full"] = "SW Model 686"
-- L["wep." .. w .. ".name"] = "SW M686"
-- L["wep." .. w .. ".desc"] = "Magnum revolver with balanced, reliable performance."
-- L["wep." .. w .. ".desc.quote"] = "When there's no more room in hell, the dead will walk the Earth."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
-- L["wep." .. w .. ".credits"] = "Assets: No More Room In Hell \nAnimations: Tactical Intervention"

w = ws .. "toz34"
-- Only has a .name.full because the weapon does.
-- L["wep." .. w .. ".name.full"] = "TOZ-34"
-- L["wep." .. w .. ".name"] = "TOZ-34"
L["wep." .. w .. ".desc"] = "Podwójna strzelba myśliwska. Ma przyzwoitą celność i siłę rażenia, ale jej rozmiar i wolne przeładowanie sprawiają, że jest nieodpowiednia do walki."
-- L["wep." .. w .. ".desc.quote"] = "\"A nu, chiki briki i v damki!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tulsky Oruzheiny Zavod"
-- L["wep." .. w .. ".credits"] = "Model: SAM61 \nSounds: rzen1th \nAnimations: speedonerd & 8Z"

w = ws .. "toz106"
-- Only has a .name.full because the weapon does.
-- L["wep." .. w .. ".name.full"] = "TOZ-106"
-- L["wep." .. w .. ".name"] = "TOZ-106"
L["wep." .. w .. ".desc"] = "Strzelba myśliwska z zamkiem ślizgowym. Małe kaliberowe pociski mają doskonałą celność, ale nie są bardzo śmiercionośne."
-- L["wep." .. w .. ".desc.quote"] = "\"Head, eyes.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tulsky Oruzheiny Zavod"
-- L["wep." .. w .. ".credits"] = "Model: RusMarine85 \nAnimations: Tactical Intervention \nPorted by: Arctic"

w = ws .. "uzi"
-- L["wep." .. w .. ".name.full"] = "IMI Uzi"
-- L["wep." .. w .. ".name"] = "Uzi"
L["wep." .. w .. ".desc"] = "Powojenny pistolet maszynowy o niesamowitej sterowalności. Jeden z najbardziej kultowych pistoletów, jakie kiedykolwiek wynaleziono. Ta wersja strzela z zamkniętym ryglem."
L["wep." .. w .. ".desc.quote"] = "\"Znasz się na swoich broniach, kumpel.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Israeli Military Industries"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Firearms: Source \nSounds: Ghost597879, Ganryu, Strelok, Sticer \nAnimations: Tactical Intervention"

w = ws .. "vykhlop"
-- L["wep." .. w .. ".name.full"] = "VKS \"Vykhlop\""
-- L["wep." .. w .. ".name"] = "VKS"
L["wep." .. w .. ".desc"] = "Poddźwiękowy karabin snajperski z potężną i szybką do przeładowania amunicją poddźwiękową, ale ma niską prędkość wylotową i słabą penetrację pancerza. Wyposażony w celownik 6x."
-- L["wep." .. w .. ".desc.quote"] = "\"Na'am seyidi, al qanas ala al khatt.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "TsKIB SOO"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Call to Arms \nAnimations: Tactical Intervention, Arctic"

w = ws .. "woodsman"
-- L["wep." .. w .. ".name.full"] = "Colt Woodsman"
-- L["wep." .. w .. ".name"] = "Woodsman"
-- L["wep." .. w .. ".desc"] = "Small caliber sporting pistol. Light and controllable enough to use one-handed, but lethality is low."
-- L["wep." .. w .. ".desc.quote"] = "\"Oh, my God, is that a .22?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Model: Kimono, Faffout \nTextures: Crash \nSounds: Vunsunta, DMG, Strelok"

-- Attachments (ak)
-- L["att.optic_sako85_4x.name.full"] = "Sako 85 4x Scope Zoom"
-- L["att.optic_sako85_4x.name"] = "4x"
-- L["att.optic_sako85_4x.desc"] = "Reduced scope magnification."

-- L["att.optic_sako85_8x.name.full"] = "Sako 85 8x Scope Zoom"
-- L["att.optic_sako85_8x.name"] = "8x"
-- L["att.optic_sako85_8x.desc"] = "Increased scope magnification."

-- L["att.optic_sako85_irons.name"] = "Iron Sights"
-- L["att.optic_sako85_irons.desc"] = "Remove scope for faster aim and better mobility."

-- L["att.ammo_sako85_222.name.full"] = "Sako 85 .222 Winchester Mod Kit"
-- L["att.ammo_sako85_222.name"] = ".222 Win"
-- L["att.ammo_sako85_222.desc"] = "Load intermediate rounds with reduced recoil and lethality."

-- L["att.ammo_sako85_300mag.name.full"] = "Sako 85 .300 Winchester Magnum Mod Kit"
-- L["att.ammo_sako85_300mag.name"] = ".300 Win Mag"
-- L["att.ammo_sako85_300mag.desc"] = "Load magnum rounds for improved lethality."

-- L["att.optic_svt_pu.name.full"] = "SVT-40 3.5x PU Scope"
-- L["att.optic_svt_pu.name"] = "PU"
-- L["att.optic_svt_pu.desc"] = "Low power scope with specialized mount for the SVT-40."

-- L["att.ammo_m202_smoke.name.full"] = "M202 Smoke Rockets"
-- L["att.ammo_m202_smoke.name"] = "Smoke"
-- L["att.ammo_m202_smoke.desc"] = "Rockets that produces a concealing smokescreen on impact."

-- L["att.ammo_m202_apers.name.full"] = "M202 Hornet Rockets"
-- L["att.ammo_m202_apers.name"] = "Hornet"
-- L["att.ammo_m202_apers.desc"] = "Airburst fragmentation rockets for direct fire anti-personnel use."

-- L["att.ammo_m202_harpoon.name.full"] = "M202 Harpoon Rockets"
-- L["att.ammo_m202_harpoon.name"] = "Harpoon"
-- L["att.ammo_m202_harpoon.desc"] = "Launch fiery harpoons that do tremendous damage on impact."

-- L["att.ammo_m202_he.name.full"] = "M202 High-Explosive Anti-Tank Rockets"
-- L["att.ammo_m202_he.name"] = "HEAT"
-- L["att.ammo_m202_he.desc"] = "Rockets with an explosive charge."

-- L["att.optic_mosin_irons.name.full"] = "Mosin-Nagant Sniper Bolt"
-- L["att.optic_mosin_irons.name"] = "Sniper"
-- L["att.optic_mosin_irons.desc"] = "Use the sniper bolt without a scope, increasing accuracy."

-- L["att.optic_mosin_pu.name.full"] = "Mosin-Nagant 3.5x PU Scope"
-- L["att.optic_mosin_pu.name"] = "PU"
-- L["att.optic_mosin_pu.desc"] = "Side-mounted low power scope for the Mosin-Nagant."

-- L["att.optic_mosin_pem.name.full"] = "Mosin-Nagant 6x PEM Scope"
-- L["att.optic_mosin_pem.name"] = "PEM"
-- L["att.optic_mosin_pem.desc"] = "Side-mounted sniper scope for the Mosin-Nagant."

-- L["att.optic_mosin_pe.name.full"] = "Mosin-Nagant 4x PE Scope"
-- L["att.optic_mosin_pe.name"] = "PE"
-- L["att.optic_mosin_pe.desc"] = "Top-mounted medium range scope for the Mosin-Nagant."

-- L["att.muzz_mosin_bayonet.name.full"] = "Mosin-Nagant Spike Bayonet"
-- L["att.muzz_mosin_bayonet.name"] = "Bayonet"
-- L["att.muzz_mosin_bayonet.desc"] = "For stabbing fascist scum."

-- L["att.muzz_svu_supp.name.full"] = "Dragunov SVU Suppressor"
-- L["att.muzz_svu_supp.name"] = "SVU Supp."
-- L["att.muzz_svu_supp.desc"] = "Weapon-specific suppressor that boosts fire rate."

-- L["att.muzz_sks_bayonet.name.full"] = "SKS Folding Bayonet"
-- L["att.muzz_sks_bayonet.name"] = "Bayonet"
-- L["att.muzz_sks_bayonet.desc"] = "For stabbing capitalist scum."

-- L["att.tac_cz75_mag.name.full"] = "CZ-75 Backup Magazine"
-- L["att.tac_cz75_mag.name"] = "Backup Mag"
-- L["att.tac_cz75_mag.desc"] = "An extra magazine mounted on the gun for peace of mind."

-- L["att.barrel_coachgun_short.name.full"] = "Coachgun Short Barrels"
-- L["att.barrel_coachgun_short.name"] = "Short"
-- L["att.barrel_coachgun_short.desc"] = "Significantly shortened barrel for close range encounters."

-- L["att.ammo_automag3_30carbine.name.full"] = "AutoMag III .30 Carbine Mod Kit"
-- L["att.ammo_automag3_30carbine.name"] = ".30 Carbine"
-- L["att.ammo_automag3_30carbine.desc"] = "Load a carbine cartridge for improved accuracy and range."

-- L["att.optic_smle_no32.name.full"] = "Lee Enfield No. 32 Telescopic Scope"
-- L["att.optic_smle_no32.name"] = "No. 32 Scope"
-- L["att.optic_smle_no32.desc"] = "Top-mounted medium range scope for the Lee-Enfield."

-- L["att.ammo_p2a1_incendiary.name.full"] = "P2A1 Incendiary Cartridges"
-- L["att.ammo_p2a1_incendiary.name"] = "Incendiary"
-- L["att.ammo_p2a1_incendiary.desc"] = "Flares with a more powerful explosion but no illumination."

-- L["att.ammo_p2a1_smoke.name.full"] = "P2A1 Smoke Cartridges"
-- L["att.ammo_p2a1_smoke.name"] = "Smoke"
-- L["att.ammo_p2a1_smoke.desc"] = "Flares that creates a small smokescreen on impact."

-- L["att.ammo_p2a1_para.name.full"] = "P2A1 Illumination Flare Cartridges"
-- L["att.ammo_p2a1_para.name"] = "Illumination"
-- L["att.ammo_p2a1_para.desc"] = "White flares with a mini-parachute, lighting up a large area while it falls."

-- L["att.ammo_p2a1_buckshot.name.full"] = "P2A1 Magnum Buck Shotshells"
-- L["att.ammo_p2a1_buckshot.name"] = "Magnum Buck"
-- L["att.ammo_p2a1_buckshot.desc"] = "Cram some shotshells into your flare gun for direct firepower."

-- L["att.ammo_p2a1_bird.name.full"] = "P2A1 Birdshot Shotshells"
-- L["att.ammo_p2a1_bird.name"] = "Birdshot"
-- L["att.ammo_p2a1_bird.desc"] = "Cram some birdshells into your flare gun. Insane spread but hard to miss."

-- L["att.ammo_p2a1_slug.name.full"] = "P2A1 Slug Shotshells"
-- L["att.ammo_p2a1_slug.desc"] = "Cram slugs into your flare gun. Short barrel limits accuracy and range."

-- L["att.ammo_p2a1_frag.name.full"] = "P2A1 High-Explosive Frag Shotshells"
-- L["att.ammo_p2a1_frag.name"] = "Frag"
-- L["att.ammo_p2a1_frag.desc"] = "Turn your flare gun into a knockoff grenade pistol."

-- L["att.ammo_p2a1_flashbang.name.full"] = "P2A1 Zvezda Flash Shotshells"
-- L["att.ammo_p2a1_flashbang.name"] = "Zvezda"
-- L["att.ammo_p2a1_flashbang.desc"] = "Flashbang dispenser in your pocket. Best used around corners."

-- L["att.ammo_p2a1_breach.name.full"] = "P2A1 Breaching Shotshells"
-- L["att.ammo_p2a1_breach.name"] = "Breach"
-- L["att.ammo_p2a1_breach.desc"] = "Load a specialized breaching slug for pocket door busting."

-- L["att.ammo_p2a1_confetti.name.full"] = "P2A1 Confetti Shotshells"
-- L["att.ammo_p2a1_confetti.name"] = "Confetti"
-- L["att.ammo_p2a1_confetti.desc"] = "For celebrations. Yippie!"

-- L["att.procon.illumradius"] = "Illumination Radius"
-- L["att.procon.noflare"] = "No Flare"