L = {} -- Swedish Content Strings by Moka

///////////////////// -- [[ Scavenger's Spoils ]] --
-- Weapons
ws = "tacrp_pa_"
w = ws .. "auto5"
L["wep." .. w .. ".name.full"] = "Browning Auto 5"
L["wep." .. w .. ".name"] = "Auto 5"
L["wep." .. w .. ".desc"] = "Gammaldags automatisk hagelbössa. Patroner med lägre kaliber har bra räckvidd och eldhastighet, men dålig stoppkraft."
L["wep." .. w .. ".desc.quote"] = "\"Få upp dem och skjut ned dem.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Browning Arms"
L["wep." .. w .. ".credits"] = "Modell: RedRogueXIII, An Aggressive Napkin \nTexturer: Futon \nLjud: Futon \nAnimationer: Tactical Intervention"

w = ws .. "automag3"
L["wep." .. w .. ".name.full"] = "AMT AutoMag III"
L["wep." .. w .. ".name"] = "AutoMag III"
L["wep." .. w .. ".desc"] = "Pistol av rostfri stål matad i en ovanlig patron. Inte lika kraftfull som en magnum-pistol, men har bra kapacitet."
L["wep." .. w .. ".desc.quote"] = "\"Du var alltid den bästa. Ingen har någonsin varit nära.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Arcadia Machine & Tool"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Degenerate Dak \nLjud: Navaro \nAnimationer: Tactical Intervention"

w = ws .. "awp"
L["wep." .. w .. ".name.full"] = "AI AWM-F"
L["wep." .. w .. ".name"] = "AWM"
L["wep." .. w .. ".desc"] = "Tuff magnum-krypskyttegevär med oöverträffad kraft och precision. En anti-terrorists favorit.\nUtrustat med ett 12x kikarsikte som standard."
L["wep." .. w .. ".desc.quote"] = "\"Han är galen, en forskare, och en krypskytt.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Accuracy International"
L["wep." .. w .. ".credits"] = "Modell: Hav0c \nTexturer: Bullethead & Kimono \nLjud: Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "coachgun"
L["wep." .. w .. ".name.full"] = "Stoeger Coachgun"
L["wep." .. w .. ".name"] = "Coachgun"
L["wep." .. w .. ".desc"] = "Dubbelpipig hagelbössa från gamle västern.\nBesvärlig och inte träffsäker, men har bra stoppkraft."
L["wep." .. w .. ".desc.quote"] = "Lås, kolv, och två rökande pipor."
L["wep." .. w .. ".trivia.manufacturer"] = "Stoeger"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Fistful of Frags (Macaroane, Paul68Rageous, Tigg) \nLjud: Fistful of Frags, rzen1th \nAnimationer: 8Z"

w = ws .. "cz75"
L["wep." .. w .. ".name.full"] = "CZ-75 Automatic"
L["wep." .. w .. ".name"] = "CZ-75"
L["wep." .. w .. ".desc"] = "Automatisk version av den avgörande \"Wonder Nine\".\nSkjuter snabbt och kontrollerbart, men låg kapacitet."
L["wep." .. w .. ".desc.quote"] = "Höjdpunkten i halvautomatisk sidovapen evolutionen."
L["wep." .. w .. ".trivia.manufacturer"] = "CZ Uherský Brod"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Arby \nLjud: Hk, Vunsunta, xLongWayHome, Strelok, Cas, IceFluxx \nAnimationer: Tactical Intervention"

w = ws .. "dual_makarov"

L["wep." .. w .. ".name"] = "Dual Makarovs"
L["wep." .. w .. ".desc"] = "Ett par sovjetiska pistoler för att kompensera den låga stoppkraften med endast en. Minimal rekyl men dödligheten är dålig förbi nära avstånd."
L["wep." .. w .. ".desc.quote"] = "\"Slutför jobbet, James! Spräng sönder dem!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Izhevsk Mechanical Plant"
L["wep." .. w .. ".credits"] = "Tillgångar: TehSnake \nLjud: Hk, Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "fnmag"
L["wep." .. w .. ".name"] = "FN MAG"
L["wep." .. w .. ".desc"] = "Kulspruta med praktiskt taget inten rörlighet men kompenserar med otrolig stoppkraft och kapacitet."
L["wep." .. w .. ".desc.quote"] = "\"Du kan inte lämna mig här med dessa... djur.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Fabrique National"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Call to Arms \nAnimationer: Tactical Intervention \nPortat av: Arctic"

w = ws .. "fort12"
L["wep." .. w .. ".name"] = "Fort-12"
L["wep." .. w .. ".desc"] = "Kosteffektiv ukrainsk pistol som sällan ses utanför östeuropa. Låg stoppkraft, men pålitlig och kan möjligtvis överleva ett antal övernaturliga katastrofer."
L["wep." .. w .. ".desc.quote"] = "Hitta Strelok. Döda Strelok?"
L["wep." .. w .. ".trivia.manufacturer"] = "RPC Fort"
L["wep." .. w .. ".credits"] = "Tillgångar: S.T.A.L.K.E.R. (portad av modderfreak) \nAnimationer: Tactical Intervention"

w = ws .. "hipoint"
L["wep." .. w .. ".name.full"] = "Hi-Point 995"
L["wep." .. w .. ".name"] = "Hi-Point"
L["wep." .. w .. ".desc"] = "Ökänd halvautomatisk pistolkaliber karbin.\nGanska kraftfull... när den fungerar, vilket den aldrig gör."
-- L["wep." .. w .. ".desc.quote"] = "\"That chandelier was expensive, asshole!!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Hi-Point Firearms"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Yumyumshisha \nLjud: Obsidian \nAnimationer: Tactical Intervention"

w = ws .. "ithaca"
L["wep." .. w .. ".name"] = "Ithaca 37"
L["wep." .. w .. ".desc"] = "Gammaldags hagelbössa som har sett båda polisiär och militär användning. Har möjligheten till snabb \"slam-fire\" men har dålig spridning och låg patronkapacitet."
L["wep." .. w .. ".desc.quote"] = "\"Vad? Det var uppenbart! Han var den röda Spionen!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Ithaca Gun Company"
L["wep." .. w .. ".credits"] = "Modell: Millenia \nTexturer: Poux \nLjud: Strelok \nAnimationer: Tactical Intervention"

w = ws .. "klin"
L["wep." .. w .. ".name.full"] = "PP-9 Klin"
L["wep." .. w .. ".name"] = "Klin"
L["wep." .. w .. ".desc"] = "Simpel, lätt och billig automatpistol.\nHar hög eldhastighet men kan få eldavbrott."
L["wep." .. w .. ".desc.quote"] = "\"Eyy, viktignyy? DRA Å' HELVETE. Ponyl?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Izhmash"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Teh Snake \nAnimationer: Tactical Intervention"

w = ws .. "ksg12"
L["wep." .. w .. ".name.full"] = "KelTec KSG"
L["wep." .. w .. ".name"] = "KSG"
L["wep." .. w .. ".desc"] = "En udda bullpup-, pumprepeter hagelbössa med dubbla magasinrör. Super hög kapacitet kompenserad med vikt."
L["wep." .. w .. ".desc.quote"] = "\"Hörru! Sluta stirra på tjejerna.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Kel-Tec CNC Industries"
L["wep." .. w .. ".credits"] = "Tillgångar: Alliance of Valiant Arms \nLjud: Infinity Ward & Navarro \nAnimationer: Tactical Intervention, edited by speedonerd"

w = ws .. "lapd"
L["wep." .. w .. ".name.full"] = "LAPD 2019 Blaster"
L["wep." .. w .. ".name"] = "LAPD 2019"
L["wep." .. w .. ".desc"] = "Vapensmedskapelse baserad på ett ikoniskt filmvapen som har utmärkt hantering och inbyggt lasersikte."
L["wep." .. w .. ".desc.quote"] = "\"En väldig upplevelse att leva i fruktan, eller hur? Så är det att vara en slav.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Steyr, Charter Arms"
L["wep." .. w .. ".credits"] = "Tillgångar: Fallout: New Vegas \nAnimationer: Tactical Intervention, Fesiug, 8Z"

w = ws .. "lewis"
L["wep." .. w .. ".name"] = "Lewiskulspruta"
L["wep." .. w .. ".desc"] = "Grytmatad, vattenkyld, lätt kulspruta med ganska litet magasin."
L["wep." .. w .. ".desc.quote"] = "\"Ur vägen, allihopa!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Lewis Automatic Machine Gun Company"
L["wep." .. w .. ".credits"] = "Tillgångar: Verdun \nAnimationer: Tactical Intervention"

w = ws .. "luty"
L["wep." .. w .. ".name.full"] = "Kulsprutepistol Luty"
L["wep." .. w .. ".name"] = "KPist. Luty"
L["wep." .. w .. ".desc"] = "Hemmagjord KPist. gjord som en protest mot brittiska vapenregler. Början av salvoeld har ökad eldhastighet som kompenserar vapnets dåliga träffsäkerhet."
L["wep." .. w .. ".desc.quote"] = "\"Låt oss aldrig dyka under den ondska läran av anti-vapenrörelsen.\""
L["wep." .. w .. ".trivia.manufacturer"] = "P.A. Luty"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Vasily \nLjud: New World Interactive, Firearms: Source \nAnimationer: Tactical Intervention"

w = ws .. "m79"
L["wep." .. w .. ".name"] = "M79"
L["wep." .. w .. ".desc"] = "Granatkastare med träkolv och lång pipa från djungeln. Träffsäker och har snabb mynningshastighet, men betydande vikt."
L["wep." .. w .. ".desc.quote"] = "\"Goooooooooooooood morgon, Vietnam!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Springfield Armory"
L["wep." .. w .. ".credits"] = "Modell: EdisLeado \nTexturer: Millenia \nLjud: Firearms: Source \nAnimationer: speedonerd & 8Z"

w = ws .. "m202"
L["wep." .. w .. ".name.full"] = "M202 FLASH"
L["wep." .. w .. ".name"] = "M202"
L["wep." .. w .. ".desc"] = "Raketgevär med fyra brandskott. Raketerna tänder fyr på måltavlor men har låg skada och sprängradie."
L["wep." .. w .. ".desc.quote"] = "\"Skjut och glöm!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Northrop Electro-Mechanical Division"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "madsen"
L["wep." .. w .. ".name"] = "Madsen M-50"
L["wep." .. w .. ".desc"] = "Kosteffektiv dansk kulsprutepistol med pålitlig stoppkraft men obekväm ergonomi. Ett sikte kan inte monteras tack vare det toppmonterade laddhandtaget."
L["wep." .. w .. ".desc.quote"] = "\"Avstår du från djävulen... och alla hans verk?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Dansk Industri Syndikat"
L["wep." .. w .. ".credits"] = "Modell & Texturer: jesamabin \nLjud: xLongWayHome \nAnimationer: Tactical Intervention, 8Z"

w = ws .. "makarov"
L["wep." .. w .. ".name.full"] = "Makarov PM"
L["wep." .. w .. ".name"] = "PM"
L["wep." .. w .. ".desc"] = "Massproducerat sovjetiskt sidovapen designad att bäras ofta och sällan skjutas. Dödligheten är dålig förbi nära avstånd."
L["wep." .. w .. ".desc.quote"] = "\"Du lyssnar på Apocalypse radio. Den enda radiostationen i närheten.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Izhevsk Mechanical Plant"
L["wep." .. w .. ".credits"] = "Tillgångar: TehSnake \nLjud: Hk, Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "mosin"
L["wep." .. w .. ".name.full"] = "Mosin-Nagant 91/30"
L["wep." .. w .. ".name"] = "M91/30"
L["wep." .. w .. ".desc"] = "Massproducerat sovjetiskt cylinderrepetergevär. Infanteri modellen är snabbare men mindre träffsäker; utrusta ett sikte för ökad träffsäkerhet med kostnad på eldhastighet."
L["wep." .. w .. ".desc.quote"] = "\"En utav två får ett gevär, den utan följer honom!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Red Orchestra 2 \nLjud: Red Orchestra 2, rzen1th \nAnimationer: Cry of Fear, Lazarus, 8Z"

w = ws .. "oa93"
L["wep." .. w .. ".name.full"] = "Olympic Arms OA-93"
L["wep." .. w .. ".name"] = "OA-93"
L["wep." .. w .. ".desc"] = "AR-15-härledd pistol med toppmonterat laddhandtag och inget bufferrör. Designad att kringgå lagen, men denna är ironiskt sett moddad att skjuta i automateld."
L["wep." .. w .. ".desc.quote"] = "\"Det mest absurda ingenjörsätt att säga 'fan ta dig!' jag någonsin sett.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Olympic Arms"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Tuuttipingu, edited by 8Z \nLjud: NightmareMutant, Teh Strelok \nAnimationer: Tactical Intervention"

w = ws .. "obrez"
L["wep." .. w .. ".name.full"] = "Remington 700 \"Obrez\""
L["wep." .. w .. ".name"] = "Obrez"
L["wep." .. w .. ".desc"] = "Avsågat jaktgevär byggt av dem sidovapen bristna för att vara en döljbar sidovapen ersättning. Modifiering skadar träffsäkerhet och räckvidd prestandan."
L["wep." .. w .. ".desc.quote"] = "\"Yippee-yay, det blir inga bröloppsklockor idag...\""
L["wep." .. w .. ".trivia.manufacturer"] = "Remington Arms, Bubba"
L["wep." .. w .. ".credits"] = "Tillgångar: Bethesda Game Studios \nAnimationer: Tactical Intervention \nPortat av: Arctic"

w = ws .. "ots33"
L["wep." .. w .. ".name.full"] = "OTs-33 Pernach"
L["wep." .. w .. ".name"] = "OTs-33"
L["wep." .. w .. ".desc"] = "Rysk automatpistol med låg rekyl och hög rörlighet, designad för paramilitära styrkor."
L["wep." .. w .. ".desc.quote"] = "\"Hoppas detta svider.\""
L["wep." .. w .. ".trivia.manufacturer"] = "KBP Instrument Design Bureau"
L["wep." .. w .. ".credits"] = "Modell: Kimono \nTexturer: Kimono, Millenia \nLjud: iFlip, Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "p2a1"
L["wep." .. w .. ".name.full"] = "HK P2A1"
L["wep." .. w .. ".name"] = "P2A1"
L["wep." .. w .. ".desc"] = "Enkelskott signalpistol för signalerings- och belysningsanvändning.\nStandard patron har en svag brand explosion. Kan ladda diverse skott, inklusive hagelskott."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell & Texturer: New World Interactive \nLjud: Raising The Bar: Redux, speedonerd \nAnimationer: 8Z"

w = ws .. "ppsh"
L["wep." .. w .. ".name"] = "PPSh-41"
L["wep." .. w .. ".desc"] = "Sovjetisk kulsprutepistol med hög eldhastighet och ganska massiv men opålitlig trummagasin. Träffsäkerhet finns inte och är valfritt."
L["wep." .. w .. ".desc.quote"] = "Ура!"
L["wep." .. w .. ".trivia.manufacturer"] = "Flertal"
L["wep." .. w .. ".credits"] = "Modell: Tripwire Interactive \nTexturer: Rus_Ivan \nAnimationer: Tactical Intervention, edited by speedonerd \nLjud: Rus_Ivan"

w = ws .. "python"
L["wep." .. w .. ".name.full"] = "Colt Python"
L["wep." .. w .. ".name"] = "Python"
L["wep." .. w .. ".desc"] = "Kvalitet revolver ned väldigt bra precision och rå kraft.\nFör att hanteras med en hand, cowboy-style."
L["wep." .. w .. ".desc.quote"] = "\"När du behöver skjuta, skjut. Prata inte.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
L["wep." .. w .. ".credits"] = "Modell: Aggressive Napkin \nTexturer: Teh Snake \nLjud: Vunsunta, XLongWayHome \nAnimationer: Tactical Intervention"

w = ws .. "rhino60ds"
L["wep." .. w .. ".name.full"] = "Chiappa Rhino 60DS"
L["wep." .. w .. ".name"] = "Rhino 60DS"
L["wep." .. w .. ".desc"] = "Modern revolver med lång pipa och hexagonell cylinder.\nSkrymmande och har en tung avtryckare, men har utmärkt rekylkontroll."
L["wep." .. w .. ".desc.quote"] = "\"Simpelt: överspecialisera, och du förökar dig i svaghet. Det är en sölig död.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Chiappa Firearms"
L["wep." .. w .. ".credits"] = "Tillgångar: Warface, portad av Dorian15 \nAnimationer: Tactical Intervention"

w = ws .. "sako85"
L["wep." .. w .. ".name"] = "Sako 85"
L["wep." .. w .. ".desc"] = "Simpelt och tufft jaktgevär utan rum för taktiskt skräp. Utrustat med ett justerbart 6x kikarsikte."
L["wep." .. w .. ".desc.quote"] = "Skaffa en tjej som älskar dig för din hjäääärna."
L["wep." .. w .. ".trivia.manufacturer"] = "SAKO"
L["wep." .. w .. ".credits"] = "Tillgångar: No More Room In Hell \nAnimationer: Tactical Intervention"

w = ws .. "scorpionevo"
L["wep." .. w .. ".name.full"] = "CZ Scorpion EVO 3"
L["wep." .. w .. ".name"] = "Scorpion EVO"
L["wep." .. w .. ".desc"] = "Modern kulsprutepistol med extremt hög eldhastighet och intensiv rekyl."
L["wep." .. w .. ".desc.quote"] = "Förvirra inte den med vz. 61."
L["wep." .. w .. ".trivia.manufacturer"] = "CZ Uherský Brod"
L["wep." .. w .. ".credits"] = "Tillgångar: Warface, Ghost1592365 \nLjud: Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "shorty"
L["wep." .. w .. ".name.full"] = "Serbu Super Shorty"
L["wep." .. w .. ".name"] = "Shorty"
L["wep." .. w .. ".desc"] = "En anpassad, ultra kort hagelbössa, gjord för extrem döljbarhet, men offrar träffsäkerhet och kapacitet. Passar i sidovapen hölstrar."
L["wep." .. w .. ".desc.quote"] = "\"Behöver du en facelift, lille pojk?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Serbu Firearms"
L["wep." .. w .. ".credits"] = "Tillgångar: Millennia \nAnimationer: Tactical Intervention \nPortat av: Arctic"

w = ws .. "sks"
L["wep." .. w .. ".name"] = "SKS"
L["wep." .. w .. ".desc"] = "Sovjetisk halvautomatiskt gevär gjord för att kompletteras med AK:n. Välbalanserad eldvapen för måttligt avstånd."
L["wep." .. w .. ".desc.quote"] = "\"Andas inte.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arsenal"
L["wep." .. w .. ".credits"] = "Tillgångar: Firearms: Source \nAnimationer: Tactical Intervention"

w = ws .. "smle"
L["wep." .. w .. ".name.full"] = "Lee-Enfield Mk III*"
L["wep." .. w .. ".name"] = "Lee-Enfield"
L["wep." .. w .. ".desc"] = "Massproducerat brittiskt cylinderrepetergevär med hög kapacitet."
L["wep." .. w .. ".desc.quote"] = "\"Det var så simpelt.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Royal Small Arms Factory"
L["wep." .. w .. ".credits"] = "Tillgångar: Cry of Fear \nAnimationer: Cry of Fear, Lazarus"

w = ws .. "stg44"
L["wep." .. w .. ".name.full"] = "Sturmgewehr 44"
L["wep." .. w .. ".name"] = "StG 44"
L["wep." .. w .. ".desc"] = "Gammaldags automatkarbin, ansedd av många att vara den första. Ganska kraftfull, men hög chans för eldavbrott."
L["wep." .. w .. ".desc.quote"] = "\"Mein karbin dödade dig inte? Jag får använda mer gas! Mer gas!\""
L["wep." .. w .. ".trivia.manufacturer"] = "C.G. Haenel"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Tuuttipingu \nLjud: Navaro, Project Reality"

w = ws .. "svt40"
L["wep." .. w .. ".name"] = "SVT-40"
L["wep." .. w .. ".desc"] = "Massproducerat halvautomatiskt gevär från andra världskriget. Opålitlig och har begränsade sikte alternativ, men har fortfarande rå kraft."
L["wep." .. w .. ".desc.quote"] = "\"Det är ett tecken på att tyskarna börjar skita ner sig!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arsenal"
L["wep." .. w .. ".credits"] = "Modell: MrRifleman \nTexturer: BuLL5H1T"

w = ws .. "svu"
L["wep." .. w .. ".name.full"] = "Dragunov SVU"
L["wep." .. w .. ".name"] = "SVU"
L["wep." .. w .. ".desc"] = "Moderniserad bullpup-modell av SVD:n. Har bra hantering men måttlig effektiv räckvidd.\nUtrustat med ett 6x kikarsikte som standard."
L["wep." .. w .. ".desc.quote"] = "\"Det handlar om perspektiv.\""
L["wep." .. w .. ".trivia.manufacturer"] = "KBP Instrument Design Bureau"
L["wep." .. w .. ".credits"] = "Tillgångar: B0T \nLjud: NightmareMutant, sHiBaN, xLongWayHome \nAnimationer: speedonerd"

w = ws .. "sw10"
L["wep." .. w .. ".name.full"] = "SW Model 10"
L["wep." .. w .. ".name"] = "SW M10"
L["wep." .. w .. ".desc"] = "Ikonisk revolver som gynnas av både snutar och kriminella.\nMatad i en icke-magnum-patron, så den är lätt att hantera men inte lika kraftfull."
L["wep." .. w .. ".desc.quote"] = "\"Vem är 'vi', polarn?\" \"Smith och Wesson, och jag.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
L["wep." .. w .. ".credits"] = "Modell: Harry Ridgeway, MediocrityGoggles \nTexturer: Millenia \nLjud: Bethesda, Obsidian \nAnimationer: Tactical Intervention"

w = ws .. "sw686"
L["wep." .. w .. ".name.full"] = "SW Model 686"
L["wep." .. w .. ".name"] = "SW M686"
L["wep." .. w .. ".desc"] = "Magnum-revolver med balanserad, pålitlig prestanda."
L["wep." .. w .. ".desc.quote"] = "När det inte finns rum kvar i helvetet så kommer dem döda gå på jorden."
L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
L["wep." .. w .. ".credits"] = "Tillgångar: No More Room In Hell \nAnimationer: Tactical Intervention"

w = ws .. "toz34"
-- Only has a .name.full because the weapon does.
L["wep." .. w .. ".name.full"] = "TOZ-34"
L["wep." .. w .. ".name"] = "TOZ-34"
L["wep." .. w .. ".desc"] = "Dubbelpipig jakthagelbössa. Har måttlig träffsäkerhet och dödlighet, men dess tyngd och sölig omladdning gör den olämplig för strid."
L["wep." .. w .. ".desc.quote"] = "\"A nu, chiki briki i v damki!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Tulsky Oruzheiny Zavod"
L["wep." .. w .. ".credits"] = "Modell: SAM61 \nLjud: rzen1th \nAnimationer: speedonerd & 8Z"

w = ws .. "toz106"
-- Only has a .name.full because the weapon does.
L["wep." .. w .. ".name.full"] = "TOZ-106"
L["wep." .. w .. ".name"] = "TOZ-106"
L["wep." .. w .. ".desc"] = "Cylinderrepeter jakthagelbössa. Hagelskott i liten kaliber har utmärkt träffsäkerhet men är inte lika dödliga."
L["wep." .. w .. ".desc.quote"] = "\"Huvud, ögon.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Tulsky Oruzheiny Zavod"
L["wep." .. w .. ".credits"] = "Modell: RusMarine85 \nAnimationer: Tactical Intervention \nPortat av: Arctic"

w = ws .. "uzi"
L["wep." .. w .. ".name.full"] = "IMI Uzi"
L["wep." .. w .. ".name"] = "Uzi"
L["wep." .. w .. ".desc"] = "Efterkrigs-kulsprutepistol med otrolig kontrollbarhet. En av världens mest ikoniska vapen någonsin."
L["wep." .. w .. ".desc.quote"] = "\"Du kan dina vapen, polarn.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Israeli Military Industries"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Firearms: Source \nLjud: Ghost597879, Ganryu, Strelok, Sticer \nAnimationer: Tactical Intervention"

w = ws .. "vykhlop"
L["wep." .. w .. ".name.full"] = "VKS \"Vykhlop\""
L["wep." .. w .. ".name"] = "VKS"
L["wep." .. w .. ".desc"] = "Subsoniskt krypskyttegevär med hög kapacitet och eldhastighet, men låg mynningshastighet och dålig hantering. Utrustat med ett 6x kikarsikte som standard."
L["wep." .. w .. ".desc.quote"] = "\"Na'am seyidi, al qanas ala al khatt.\""
L["wep." .. w .. ".trivia.manufacturer"] = "TsKIB SOO"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Call to Arms \nAnimationer: Tactical Intervention, Arctic"

w = ws .. "woodsman"
L["wep." .. w .. ".name.full"] = "Colt Woodsman"
L["wep." .. w .. ".name"] = "Woodsman"
L["wep." .. w .. ".desc"] = "Sportpistol i liten kaliber. Lätt och kontrollerbar nog att användas med en hand, men dödligheten är låg."
L["wep." .. w .. ".desc.quote"] = "\"Men herre gud, är det där en .22:a?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
L["wep." .. w .. ".credits"] = "Modell: Kimono, Faffout \nTexturer: Crash \nLjud: Vunsunta, DMG, Strelok"

-- Attachments (ak)
L["att.optic_sako85_4x.name.full"] = "Sako 85 4x Zoom-Räckvidd"
L["att.optic_sako85_4x.name"] = "4x"
L["att.optic_sako85_4x.desc"] = "Sänkt magnifiering i siktet."

L["att.optic_sako85_8x.name.full"] = "Sako 85 8x Zoom-Räckvidd"
L["att.optic_sako85_8x.name"] = "8x"
L["att.optic_sako85_8x.desc"] = "Ökad magnifiering i siktet."

L["att.optic_sako85_irons.name"] = "Järn & Korn"
L["att.optic_sako85_irons.desc"] = "Tar bort kikarsiktet för snabbare siktetid och bättre rörlighet."

L["att.ammo_sako85_222.name.full"] = "Sako 85 .222 Winchester Modd Kit"
L["att.ammo_sako85_222.name"] = ".222 Win"
L["att.ammo_sako85_222.desc"] = "Ladda mellanliggande patroner med sänkt rekyl och dödlighet."

L["att.ammo_sako85_300mag.name.full"] = "Sako 85 .300 Winchester Magnum Modd Kit"
L["att.ammo_sako85_300mag.name"] = ".300 Win Mag"
L["att.ammo_sako85_300mag.desc"] = "Ladda magnum-patroner för ökad dödlighet."

L["att.optic_svt_pu.name.full"] = "SVT-40 3,5x PU-Sikte"
L["att.optic_svt_pu.name"] = "PU"
L["att.optic_svt_pu.desc"] = "Sikte med låg kraft med speciell montering till SVT-40:n."

L["att.ammo_m202_smoke.name.full"] = "M202 Rök Raketer"
L["att.ammo_m202_smoke.name"] = "Rök"
L["att.ammo_m202_smoke.desc"] = "Raketer som producerar en täckande rökskärm vid träff."

L["att.ammo_m202_apers.name.full"] = "M202 Hornet-Raketer"
L["att.ammo_m202_apers.name"] = "Hornet"
L["att.ammo_m202_apers.desc"] = "Splittergranat raketer som sprängs i luften dör direkt eld antipersonal användning."

L["att.ammo_m202_harpoon.name.full"] = "M202 Harpun Raketer"
L["att.ammo_m202_harpoon.name"] = "Harpun"
L["att.ammo_m202_harpoon.desc"] = "Skjuter brinnande harpuner som gör otrolig skada vid träff."

L["att.ammo_m202_he.name.full"] = "M202 Pansarsprängraketer"
L["att.ammo_m202_he.name"] = "RSV"
L["att.ammo_m202_he.desc"] = "Raketer med en explosiv laddning."

L["att.optic_mosin_irons.name.full"] = "Mosin-Nagant Krypskytte Slutstycke"
L["att.optic_mosin_irons.name"] = "Krypskytt."
L["att.optic_mosin_irons.desc"] = "Använd krypskyttegevär slutstycket utan ett sikte som ökar träffsäkerheten."

L["att.optic_mosin_pu.name.full"] = "Mosin-Nagant 3,5x PU-Sikte"
L["att.optic_mosin_pu.name"] = "PU"
L["att.optic_mosin_pu.desc"] = "Sidomonterat sikte med låg kraft till Mosin-Nagant:en."

L["att.optic_mosin_pem.name.full"] = "Mosin-Nagant 6x PEM-Sikte"
L["att.optic_mosin_pem.name"] = "PEM"
L["att.optic_mosin_pem.desc"] = "Sidomonterat kikarsikte till Mosin-Nagant:en."

L["att.optic_mosin_pe.name.full"] = "Mosin-Nagant 4x PE-Sikte"
L["att.optic_mosin_pe.name"] = "PE"
L["att.optic_mosin_pe.desc"] = "Toppmonterat sikte för måttligt avstånd till Mosin-Nagant:en."

L["att.muzz_mosin_bayonet.name.full"] = "Mosin-Nagant Spikbajonett"
L["att.muzz_mosin_bayonet.name"] = "Bajonett"
L["att.muzz_mosin_bayonet.desc"] = "För att knivhugga fascist skitstövlar."

L["att.muzz_svu_supp.name.full"] = "Dragunov SVU Ljuddämpare"
L["att.muzz_svu_supp.name"] = "SVU Ljud."
L["att.muzz_svu_supp.desc"] = "Vapenspecifik ljuddämpar som ökar eldhastigheten."

L["att.muzz_sks_bayonet.name.full"] = "SKS Vikbar Bajonett"
L["att.muzz_sks_bayonet.name"] = "Bajonett"
L["att.muzz_sks_bayonet.desc"] = "För att knivhugga kapitalist skitstövlar."

L["att.tac_cz75_mag.name.full"] = "CZ-75 Reservmagasin"
L["att.tac_cz75_mag.name"] = "Reservmag"
L["att.tac_cz75_mag.desc"] = "Ett extra magasin monterat på vapnet för sinnesfrid."

L["att.barrel_coachgun_short.name.full"] = "Coachgun Korta Pipor"
L["att.barrel_coachgun_short.name"] = "Kort"
L["att.barrel_coachgun_short.desc"] = "Ganska förkortad pipa för motstånd på nära avstånd."

L["att.ammo_automag3_30carbine.name.full"] = "AutoMag III .30 Carbine Modd Kit"
L["att.ammo_automag3_30carbine.name"] = ".30 Carbine"
L["att.ammo_automag3_30carbine.desc"] = "Ladda en karbinpatron för förbättrad träffsäkerhet och räckvidd."

L["att.optic_smle_no32.name.full"] = "Lee Enfield No. 32 Teleskopiskt Sikte"
L["att.optic_smle_no32.name"] = "No. 32 Sikte"
L["att.optic_smle_no32.desc"] = "Toppmonterat sikte för måttligt avstånd till Lee-Enfield:en."

L["att.ammo_p2a1_incendiary.name.full"] = "P2A1 Brandskott"
L["att.ammo_p2a1_incendiary.name"] = "Brand"
L["att.ammo_p2a1_incendiary.desc"] = "Signalskott med större sprängning men utan belysning."

L["att.ammo_p2a1_smoke.name.full"] = "P2A1 Rökskott"
L["att.ammo_p2a1_smoke.name"] = "Rök"
L["att.ammo_p2a1_smoke.desc"] = "Signalskott som skapar en liten rökskärm vid träff."

L["att.ammo_p2a1_para.name.full"] = "P2A1 Belysningskott"
L["att.ammo_p2a1_para.name"] = "Belysning"
L["att.ammo_p2a1_para.desc"] = "Vita signalskott med litet fallskärm som lyser upp ett område när den faller."

L["att.ammo_p2a1_buckshot.name.full"] = "P2A1 Magnum Hagelskott"
L["att.ammo_p2a1_buckshot.name"] = "Magnum"
L["att.ammo_p2a1_buckshot.desc"] = "Släng in lite hagelskott i din signalpistol för direkt stoppkraft."

L["att.ammo_p2a1_bird.name.full"] = "P2A1 Fågelskott"
L["att.ammo_p2a1_bird.name"] = "Fågelskott"
L["att.ammo_p2a1_bird.desc"] = "Släng in lite fågelskott i din signalpistol. Otrolig spridning men svårt att missa."

L["att.ammo_p2a1_slug.name.full"] = "P2A1 Sluggpatroner"
L["att.ammo_p2a1_slug.desc"] = "Släng in lite sluggpatroner i din signalpistol. Korta pipan begränsar träffsäkerheten och räckvidden."

L["att.ammo_p2a1_frag.name.full"] = "P2A1 Splittergranat Patroner"
L["att.ammo_p2a1_frag.name"] = "Splitter"
L["att.ammo_p2a1_frag.desc"] = "Förvandla din signalpistol in till en knockoff granatpistol."

L["att.ammo_p2a1_flashbang.name.full"] = "P2A1 Zvezda-Chockgranatskott"
L["att.ammo_p2a1_flashbang.name"] = "Zvezda"
L["att.ammo_p2a1_flashbang.desc"] = "Chockgranatbutik i din ficka. Används bäst runt hörn."

L["att.ammo_p2a1_breach.name.full"] = "P2A1 Dörrbrytande Patroner"
L["att.ammo_p2a1_breach.name"] = "Bryt"
L["att.ammo_p2a1_breach.desc"] = "Ladda speciella dörrbrytande sluggpatroner för dörrbrytning i fickpaket."

L["att.ammo_p2a1_confetti.name.full"] = "P2A1 Konfetti Patroner"
L["att.ammo_p2a1_confetti.name"] = "Konfetti"
L["att.ammo_p2a1_confetti.desc"] = "Till firanden. Yippie!"

L["att.procon.illumradius"] = "Belysningsradie"
L["att.procon.noflare"] = "Inga Signalskott"